import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { OrderedAsteroidsProvider } from '@/context/OrderedAsteroidsContext'
import { Header } from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Armageddon 2023',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="ru">
            <OrderedAsteroidsProvider>
                <body className={inter.className}>
                    <Header/>
                    {children}</body>
            </OrderedAsteroidsProvider>
        </html>
    )
}
